-- Create table
CREATE TABLE parts (
  part_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
  part_name VARCHAR(50) NOT NULL,
  lead_time NUMBER(2,0) NOT NULL,
  cost NUMBER(9,2) NOT NULL,
  status NUMBER(1,0) NOT NULL,
  PRIMARY KEY (part_id)
);

-- Insert test data
INSERT INTO parts (part_name,lead_time,cost,status) VALUES ('sed dictum',5,130,0);
INSERT INTO parts (part_name,lead_time,cost,status) VALUES ('tristique neque',3,62,1);
INSERT INTO parts (part_name,lead_time,cost,status) VALUES ('dolor quam,',16,82,1);
INSERT INTO parts (part_name,lead_time,cost,status) VALUES ('nec, diam.',41,10,1);

-- Data manipulation using Update statement

UPDATE parts SET cost = 130 WHERE part_id = 1;

SELECT * FROM parts WHERE part_id = 1;

UPDATE parts SET cost = cost * 1.05;

